//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Scallop/AxisCameraSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="Scallop/AxisCameraSchema.xsd", IsNullable=false)]
public partial class AxisCameraConfigSet {
    
    private AxisCameraConfigType[] itemsField;
    
    private string defaultConfigField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AxisCameraConfig")]
    public AxisCameraConfigType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DefaultConfig {
        get {
            return this.defaultConfigField;
        }
        set {
            this.defaultConfigField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="Scallop/AxisCameraSchema.xsd")]
public partial class AxisCameraConfigType {
    
    private string addressField;
    
    private AxisCameraConfigTypeCamera cameraField;
    
    private bool cameraFieldSpecified;
    
    private bool colorField;
    
    private bool colorFieldSpecified;
    
    private int colorLevelField;
    
    private bool colorLevelFieldSpecified;
    
    private int compressionField;
    
    private bool compressionFieldSpecified;
    
    private string customCgiStringField;
    
    private int framerateField;
    
    private bool framerateFieldSpecified;
    
    private string overlayPositionField;
    
    private string passwordField;
    
    private AxisCameraConfigTypeResolution resolutionField;
    
    private bool resolutionFieldSpecified;
    
    private int rotationField;
    
    private bool rotationFieldSpecified;
    
    private bool showClockField;
    
    private bool showClockFieldSpecified;
    
    private bool showDateField;
    
    private bool showDateFieldSpecified;
    
    private bool showOverlayField;
    
    private bool showOverlayFieldSpecified;
    
    private bool showTextField;
    
    private bool showTextFieldSpecified;
    
    private string textField;
    
    private AxisCameraConfigTypeTextBackgroundColor textBackgroundColorField;
    
    private bool textBackgroundColorFieldSpecified;
    
    private AxisCameraConfigTypeTextColor textColorField;
    
    private bool textColorFieldSpecified;
    
    private AxisCameraConfigTypeTextPosition textPositionField;
    
    private bool textPositionFieldSpecified;
    
    private string userField;
    
    private AxisCameraConfigTypeFrameFormat frameFormatField;
    
    private string configNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public AxisCameraConfigTypeCamera Camera {
        get {
            return this.cameraField;
        }
        set {
            this.cameraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CameraSpecified {
        get {
            return this.cameraFieldSpecified;
        }
        set {
            this.cameraFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool Color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ColorSpecified {
        get {
            return this.colorFieldSpecified;
        }
        set {
            this.colorFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int ColorLevel {
        get {
            return this.colorLevelField;
        }
        set {
            this.colorLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ColorLevelSpecified {
        get {
            return this.colorLevelFieldSpecified;
        }
        set {
            this.colorLevelFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int Compression {
        get {
            return this.compressionField;
        }
        set {
            this.compressionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CompressionSpecified {
        get {
            return this.compressionFieldSpecified;
        }
        set {
            this.compressionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string CustomCgiString {
        get {
            return this.customCgiStringField;
        }
        set {
            this.customCgiStringField = value;
        }
    }
    
    /// <remarks/>
    public int Framerate {
        get {
            return this.framerateField;
        }
        set {
            this.framerateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FramerateSpecified {
        get {
            return this.framerateFieldSpecified;
        }
        set {
            this.framerateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string OverlayPosition {
        get {
            return this.overlayPositionField;
        }
        set {
            this.overlayPositionField = value;
        }
    }
    
    /// <remarks/>
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    public AxisCameraConfigTypeResolution Resolution {
        get {
            return this.resolutionField;
        }
        set {
            this.resolutionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ResolutionSpecified {
        get {
            return this.resolutionFieldSpecified;
        }
        set {
            this.resolutionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int Rotation {
        get {
            return this.rotationField;
        }
        set {
            this.rotationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RotationSpecified {
        get {
            return this.rotationFieldSpecified;
        }
        set {
            this.rotationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool ShowClock {
        get {
            return this.showClockField;
        }
        set {
            this.showClockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ShowClockSpecified {
        get {
            return this.showClockFieldSpecified;
        }
        set {
            this.showClockFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool ShowDate {
        get {
            return this.showDateField;
        }
        set {
            this.showDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ShowDateSpecified {
        get {
            return this.showDateFieldSpecified;
        }
        set {
            this.showDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool ShowOverlay {
        get {
            return this.showOverlayField;
        }
        set {
            this.showOverlayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ShowOverlaySpecified {
        get {
            return this.showOverlayFieldSpecified;
        }
        set {
            this.showOverlayFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool ShowText {
        get {
            return this.showTextField;
        }
        set {
            this.showTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ShowTextSpecified {
        get {
            return this.showTextFieldSpecified;
        }
        set {
            this.showTextFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    public AxisCameraConfigTypeTextBackgroundColor TextBackgroundColor {
        get {
            return this.textBackgroundColorField;
        }
        set {
            this.textBackgroundColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TextBackgroundColorSpecified {
        get {
            return this.textBackgroundColorFieldSpecified;
        }
        set {
            this.textBackgroundColorFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public AxisCameraConfigTypeTextColor TextColor {
        get {
            return this.textColorField;
        }
        set {
            this.textColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TextColorSpecified {
        get {
            return this.textColorFieldSpecified;
        }
        set {
            this.textColorFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public AxisCameraConfigTypeTextPosition TextPosition {
        get {
            return this.textPositionField;
        }
        set {
            this.textPositionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TextPositionSpecified {
        get {
            return this.textPositionFieldSpecified;
        }
        set {
            this.textPositionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string User {
        get {
            return this.userField;
        }
        set {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    public AxisCameraConfigTypeFrameFormat FrameFormat {
        get {
            return this.frameFormatField;
        }
        set {
            this.frameFormatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ConfigName {
        get {
            return this.configNameField;
        }
        set {
            this.configNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Scallop/AxisCameraSchema.xsd")]
public enum AxisCameraConfigTypeCamera {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    quad,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Scallop/AxisCameraSchema.xsd")]
public enum AxisCameraConfigTypeResolution {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1280x1024")]
    Item1280x1024,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1280x960")]
    Item1280x960,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1280x720")]
    Item1280x720,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("768x576")]
    Item768x576,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4CIF")]
    Item4CIF,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("704x576")]
    Item704x576,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("704x480")]
    Item704x480,
    
    /// <remarks/>
    VGA,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("640x480")]
    Item640x480,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("640x360")]
    Item640x360,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2CIFEXP")]
    Item2CIFEXP,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2CIF")]
    Item2CIF,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("704x288")]
    Item704x288,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("704x240")]
    Item704x240,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("480x360")]
    Item480x360,
    
    /// <remarks/>
    CIF,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("384x288")]
    Item384x288,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("352x288")]
    Item352x288,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("352x240")]
    Item352x240,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("320x240")]
    Item320x240,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("240x180")]
    Item240x180,
    
    /// <remarks/>
    QCIF,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("192x144")]
    Item192x144,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("176x144")]
    Item176x144,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("176x120")]
    Item176x120,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("160x120")]
    Item160x120,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Scallop/AxisCameraSchema.xsd")]
public enum AxisCameraConfigTypeTextBackgroundColor {
    
    /// <remarks/>
    black,
    
    /// <remarks/>
    white,
    
    /// <remarks/>
    transparent,
    
    /// <remarks/>
    semitransparent,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Scallop/AxisCameraSchema.xsd")]
public enum AxisCameraConfigTypeTextColor {
    
    /// <remarks/>
    black,
    
    /// <remarks/>
    white,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Scallop/AxisCameraSchema.xsd")]
public enum AxisCameraConfigTypeTextPosition {
    
    /// <remarks/>
    top,
    
    /// <remarks/>
    bottom,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Scallop/AxisCameraSchema.xsd")]
public enum AxisCameraConfigTypeFrameFormat {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("System.Drawing.Bitmap")]
    SystemDrawingBitmap,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("System.Windows.Media.Imaging.BitmapSource")]
    SystemWindowsMediaImagingBitmapSource,
    
    /// <remarks/>
    Jpeg,
}
