//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 

namespace Scallop.Network.PeerChannel
{
   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "Scallop/PeerChannelConfig.xsd")]
   [System.Xml.Serialization.XmlRootAttribute(Namespace = "Scallop/PeerChannelConfig.xsd", IsNullable = false)]
   public partial class PeerChannelConfigSet
   {

      private PeerChannelConfigType[] itemsField;

      private string defaultConfigField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("PeerChannelConfig")]
      public PeerChannelConfigType[] Items
      {
         get
         {
            return this.itemsField;
         }
         set
         {
            this.itemsField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string DefaultConfig
      {
         get
         {
            return this.defaultConfigField;
         }
         set
         {
            this.defaultConfigField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "Scallop/PeerChannelConfig.xsd")]
   public partial class PeerChannelConfigType
   {

      private string nodeIdField;

      private string networkNameField;

      private string networkAddressField;

      private bool enableTransportSecurityField;

      private bool enableTransportSecurityFieldSpecified;

      private string tLSPasswordField;

      private int neighborQueryRateField;

      private bool neighborQueryRateFieldSpecified;

      private string configNameField;

      /// <remarks/>
      public string NodeId
      {
         get
         {
            return this.nodeIdField;
         }
         set
         {
            this.nodeIdField = value;
         }
      }

      /// <remarks/>
      public string NetworkName
      {
         get
         {
            return this.networkNameField;
         }
         set
         {
            this.networkNameField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
      public string NetworkAddress
      {
         get
         {
            return this.networkAddressField;
         }
         set
         {
            this.networkAddressField = value;
         }
      }

      /// <remarks/>
      public bool EnableTransportSecurity
      {
         get
         {
            return this.enableTransportSecurityField;
         }
         set
         {
            this.enableTransportSecurityField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool EnableTransportSecuritySpecified
      {
         get
         {
            return this.enableTransportSecurityFieldSpecified;
         }
         set
         {
            this.enableTransportSecurityFieldSpecified = value;
         }
      }

      /// <remarks/>
      public string TLSPassword
      {
         get
         {
            return this.tLSPasswordField;
         }
         set
         {
            this.tLSPasswordField = value;
         }
      }

      /// <remarks/>
      public int NeighborQueryRate
      {
         get
         {
            return this.neighborQueryRateField;
         }
         set
         {
            this.neighborQueryRateField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool NeighborQueryRateSpecified
      {
         get
         {
            return this.neighborQueryRateFieldSpecified;
         }
         set
         {
            this.neighborQueryRateFieldSpecified = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string ConfigName
      {
         get
         {
            return this.configNameField;
         }
         set
         {
            this.configNameField = value;
         }
      }
   }
}
